// Code generated by protoc-gen-go.
// source: category/category.proto
// DO NOT EDIT!

/*
Package category is a generated protocol buffer package.

It is generated from these files:
	category/category.proto

It has these top-level messages:
	CategoryResult
	Category
*/
package category

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// CategoryResult 商品分类
type CategoryResult struct {
	Categories []*Category `protobuf:"bytes,1,rep,name=categories" json:"categories,omitempty"`
}

func (m *CategoryResult) Reset()                    { *m = CategoryResult{} }
func (m *CategoryResult) String() string            { return proto.CompactTextString(m) }
func (*CategoryResult) ProtoMessage()               {}
func (*CategoryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CategoryResult) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type Category struct {
	ID         uint32 `protobuf:"varint,1,opt,name=iD" json:"iD,omitempty"`
	MobileName string `protobuf:"bytes,2,opt,name=mobileName" json:"mobileName,omitempty"`
}

func (m *Category) Reset()                    { *m = Category{} }
func (m *Category) String() string            { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()               {}
func (*Category) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*CategoryResult)(nil), "category.CategoryResult")
	proto.RegisterType((*Category)(nil), "category.Category")
}

func init() { proto.RegisterFile("category/category.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0x4e, 0x2c, 0x49,
	0x4d, 0xcf, 0x2f, 0xaa, 0xd4, 0x87, 0x31, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38, 0x60,
	0x7c, 0x25, 0x17, 0x2e, 0x3e, 0x67, 0x28, 0x3b, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x44, 0xc8, 0x88,
	0x8b, 0x0b, 0x2a, 0x9b, 0x99, 0x5a, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xa4, 0x07,
	0x37, 0x00, 0xae, 0x1a, 0x49, 0x95, 0x92, 0x15, 0x17, 0x07, 0x4c, 0x5c, 0x88, 0x8f, 0x8b, 0x29,
	0xd3, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x37, 0x88, 0x29, 0xd3, 0x45, 0x48, 0x8e, 0x8b, 0x2b,
	0x37, 0x3f, 0x29, 0x33, 0x27, 0xd5, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33,
	0x08, 0x49, 0x24, 0x89, 0x0d, 0xec, 0x24, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x93,
	0xb9, 0xa0, 0xad, 0x00, 0x00, 0x00,
}
