// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order/order.proto

/*
Package order is a generated protocol buffer package.

It is generated from these files:
	order/order.proto

It has these top-level messages:
	CreateParam
	Order
	List
	Address
	Detail
*/
package order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateParam struct {
	AddressID uint32 `protobuf:"varint,1,opt,name=addressID" json:"addressID,omitempty"`
	Remark    string `protobuf:"bytes,2,opt,name=remark" json:"remark,omitempty"`
}

func (m *CreateParam) Reset()                    { *m = CreateParam{} }
func (m *CreateParam) String() string            { return proto.CompactTextString(m) }
func (*CreateParam) ProtoMessage()               {}
func (*CreateParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateParam) GetAddressID() uint32 {
	if m != nil {
		return m.AddressID
	}
	return 0
}

func (m *CreateParam) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

// Order 订单
type Order struct {
	ID          uint32  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	OrderSN     string  `protobuf:"bytes,2,opt,name=orderSN" json:"orderSN,omitempty"`
	TotalAmount float32 `protobuf:"fixed32,3,opt,name=totalAmount" json:"totalAmount,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Order) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Order) GetOrderSN() string {
	if m != nil {
		return m.OrderSN
	}
	return ""
}

func (m *Order) GetTotalAmount() float32 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

type List struct {
	Orders []*List_OrderWithGoods `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
}

func (m *List) Reset()                    { *m = List{} }
func (m *List) String() string            { return proto.CompactTextString(m) }
func (*List) ProtoMessage()               {}
func (*List) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *List) GetOrders() []*List_OrderWithGoods {
	if m != nil {
		return m.Orders
	}
	return nil
}

type List_OrderWithGoods struct {
	Order   *List_OrderWithGoods_Order   `protobuf:"bytes,1,opt,name=order" json:"order,omitempty"`
	Goodses []*List_OrderWithGoods_Goods `protobuf:"bytes,2,rep,name=goodses" json:"goodses,omitempty"`
}

func (m *List_OrderWithGoods) Reset()                    { *m = List_OrderWithGoods{} }
func (m *List_OrderWithGoods) String() string            { return proto.CompactTextString(m) }
func (*List_OrderWithGoods) ProtoMessage()               {}
func (*List_OrderWithGoods) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *List_OrderWithGoods) GetOrder() *List_OrderWithGoods_Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *List_OrderWithGoods) GetGoodses() []*List_OrderWithGoods_Goods {
	if m != nil {
		return m.Goodses
	}
	return nil
}

type List_OrderWithGoods_Order struct {
	ID            uint32  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	OrderState    uint32  `protobuf:"varint,2,opt,name=orderState" json:"orderState,omitempty"`
	OrderSN       string  `protobuf:"bytes,3,opt,name=orderSN" json:"orderSN,omitempty"`
	ShippingState uint32  `protobuf:"varint,4,opt,name=shippingState" json:"shippingState,omitempty"`
	PayState      uint32  `protobuf:"varint,5,opt,name=payState" json:"payState,omitempty"`
	GoodsPrice    float32 `protobuf:"fixed32,6,opt,name=goodsPrice" json:"goodsPrice,omitempty"`
	ShippingPrice float32 `protobuf:"fixed32,7,opt,name=shippingPrice" json:"shippingPrice,omitempty"`
	OrderAmount   float32 `protobuf:"fixed32,8,opt,name=orderAmount" json:"orderAmount,omitempty"`
	TotalAmount   float32 `protobuf:"fixed32,9,opt,name=totalAmount" json:"totalAmount,omitempty"`
	AddTime       string  `protobuf:"bytes,10,opt,name=addTime" json:"addTime,omitempty"`
	UserNote      string  `protobuf:"bytes,11,opt,name=userNote" json:"userNote,omitempty"`
	AdminNote     string  `protobuf:"bytes,12,opt,name=adminNote" json:"adminNote,omitempty"`
	StateName     string  `protobuf:"bytes,13,opt,name=stateName" json:"stateName,omitempty"`
}

func (m *List_OrderWithGoods_Order) Reset()                    { *m = List_OrderWithGoods_Order{} }
func (m *List_OrderWithGoods_Order) String() string            { return proto.CompactTextString(m) }
func (*List_OrderWithGoods_Order) ProtoMessage()               {}
func (*List_OrderWithGoods_Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0, 0} }

func (m *List_OrderWithGoods_Order) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *List_OrderWithGoods_Order) GetOrderState() uint32 {
	if m != nil {
		return m.OrderState
	}
	return 0
}

func (m *List_OrderWithGoods_Order) GetOrderSN() string {
	if m != nil {
		return m.OrderSN
	}
	return ""
}

func (m *List_OrderWithGoods_Order) GetShippingState() uint32 {
	if m != nil {
		return m.ShippingState
	}
	return 0
}

func (m *List_OrderWithGoods_Order) GetPayState() uint32 {
	if m != nil {
		return m.PayState
	}
	return 0
}

func (m *List_OrderWithGoods_Order) GetGoodsPrice() float32 {
	if m != nil {
		return m.GoodsPrice
	}
	return 0
}

func (m *List_OrderWithGoods_Order) GetShippingPrice() float32 {
	if m != nil {
		return m.ShippingPrice
	}
	return 0
}

func (m *List_OrderWithGoods_Order) GetOrderAmount() float32 {
	if m != nil {
		return m.OrderAmount
	}
	return 0
}

func (m *List_OrderWithGoods_Order) GetTotalAmount() float32 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *List_OrderWithGoods_Order) GetAddTime() string {
	if m != nil {
		return m.AddTime
	}
	return ""
}

func (m *List_OrderWithGoods_Order) GetUserNote() string {
	if m != nil {
		return m.UserNote
	}
	return ""
}

func (m *List_OrderWithGoods_Order) GetAdminNote() string {
	if m != nil {
		return m.AdminNote
	}
	return ""
}

func (m *List_OrderWithGoods_Order) GetStateName() string {
	if m != nil {
		return m.StateName
	}
	return ""
}

type List_OrderWithGoods_Goods struct {
	ID          uint32  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	OrderID     uint32  `protobuf:"varint,2,opt,name=orderID" json:"orderID,omitempty"`
	GoodsID     uint32  `protobuf:"varint,3,opt,name=goodsID" json:"goodsID,omitempty"`
	GoodsName   string  `protobuf:"bytes,4,opt,name=goodsName" json:"goodsName,omitempty"`
	GoodsNum    uint32  `protobuf:"varint,5,opt,name=goodsNum" json:"goodsNum,omitempty"`
	GoodsPrice  float32 `protobuf:"fixed32,6,opt,name=goodsPrice" json:"goodsPrice,omitempty"`
	CostPrice   float32 `protobuf:"fixed32,7,opt,name=costPrice" json:"costPrice,omitempty"`
	SpecKeyName string  `protobuf:"bytes,8,opt,name=specKeyName" json:"specKeyName,omitempty"`
}

func (m *List_OrderWithGoods_Goods) Reset()                    { *m = List_OrderWithGoods_Goods{} }
func (m *List_OrderWithGoods_Goods) String() string            { return proto.CompactTextString(m) }
func (*List_OrderWithGoods_Goods) ProtoMessage()               {}
func (*List_OrderWithGoods_Goods) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0, 1} }

func (m *List_OrderWithGoods_Goods) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *List_OrderWithGoods_Goods) GetOrderID() uint32 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

func (m *List_OrderWithGoods_Goods) GetGoodsID() uint32 {
	if m != nil {
		return m.GoodsID
	}
	return 0
}

func (m *List_OrderWithGoods_Goods) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *List_OrderWithGoods_Goods) GetGoodsNum() uint32 {
	if m != nil {
		return m.GoodsNum
	}
	return 0
}

func (m *List_OrderWithGoods_Goods) GetGoodsPrice() float32 {
	if m != nil {
		return m.GoodsPrice
	}
	return 0
}

func (m *List_OrderWithGoods_Goods) GetCostPrice() float32 {
	if m != nil {
		return m.CostPrice
	}
	return 0
}

func (m *List_OrderWithGoods_Goods) GetSpecKeyName() string {
	if m != nil {
		return m.SpecKeyName
	}
	return ""
}

type Address struct {
	ProvinceStr string `protobuf:"bytes,1,opt,name=provinceStr" json:"provinceStr,omitempty"`
	CityStr     string `protobuf:"bytes,2,opt,name=cityStr" json:"cityStr,omitempty"`
	DistrictStr string `protobuf:"bytes,3,opt,name=districtStr" json:"districtStr,omitempty"`
	TwonStr     string `protobuf:"bytes,4,opt,name=twonStr" json:"twonStr,omitempty"`
	Consignee   string `protobuf:"bytes,5,opt,name=consignee" json:"consignee,omitempty"`
	Mobile      string `protobuf:"bytes,6,opt,name=mobile" json:"mobile,omitempty"`
	Address     string `protobuf:"bytes,7,opt,name=address" json:"address,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Address) GetProvinceStr() string {
	if m != nil {
		return m.ProvinceStr
	}
	return ""
}

func (m *Address) GetCityStr() string {
	if m != nil {
		return m.CityStr
	}
	return ""
}

func (m *Address) GetDistrictStr() string {
	if m != nil {
		return m.DistrictStr
	}
	return ""
}

func (m *Address) GetTwonStr() string {
	if m != nil {
		return m.TwonStr
	}
	return ""
}

func (m *Address) GetConsignee() string {
	if m != nil {
		return m.Consignee
	}
	return ""
}

func (m *Address) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Detail struct {
	OrderWithGoods *List_OrderWithGoods `protobuf:"bytes,1,opt,name=orderWithGoods" json:"orderWithGoods,omitempty"`
	Address        *Address             `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *Detail) Reset()                    { *m = Detail{} }
func (m *Detail) String() string            { return proto.CompactTextString(m) }
func (*Detail) ProtoMessage()               {}
func (*Detail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Detail) GetOrderWithGoods() *List_OrderWithGoods {
	if m != nil {
		return m.OrderWithGoods
	}
	return nil
}

func (m *Detail) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateParam)(nil), "order.CreateParam")
	proto.RegisterType((*Order)(nil), "order.Order")
	proto.RegisterType((*List)(nil), "order.List")
	proto.RegisterType((*List_OrderWithGoods)(nil), "order.List.OrderWithGoods")
	proto.RegisterType((*List_OrderWithGoods_Order)(nil), "order.List.OrderWithGoods.Order")
	proto.RegisterType((*List_OrderWithGoods_Goods)(nil), "order.List.OrderWithGoods.Goods")
	proto.RegisterType((*Address)(nil), "order.Address")
	proto.RegisterType((*Detail)(nil), "order.Detail")
}

func init() { proto.RegisterFile("order/order.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 574 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcd, 0x6a, 0xdb, 0x40,
	0x10, 0x46, 0x72, 0x2c, 0x47, 0xe3, 0xda, 0xd0, 0x3d, 0x14, 0x61, 0x42, 0x11, 0xa6, 0x07, 0x9f,
	0x52, 0x48, 0xa1, 0x87, 0xde, 0xd2, 0x18, 0x8a, 0x69, 0x49, 0x83, 0x52, 0xe8, 0x59, 0x91, 0x16,
	0x67, 0xa9, 0xa5, 0x15, 0xbb, 0xeb, 0x14, 0x3f, 0x45, 0x1f, 0xa8, 0x4f, 0xd1, 0x87, 0xe8, 0x6b,
	0x94, 0x32, 0x33, 0x2b, 0x59, 0x4e, 0x71, 0x7a, 0x31, 0xfe, 0xbe, 0x99, 0x4f, 0xdf, 0xce, 0xcf,
	0x2e, 0x3c, 0xd7, 0xa6, 0x94, 0xe6, 0x35, 0xfd, 0x9e, 0x37, 0x46, 0x3b, 0x2d, 0x86, 0x04, 0xe6,
	0x57, 0x30, 0xbe, 0x32, 0x32, 0x77, 0xf2, 0x26, 0x37, 0x79, 0x25, 0xce, 0x20, 0xce, 0xcb, 0xd2,
	0x48, 0x6b, 0x57, 0xcb, 0x24, 0x48, 0x83, 0xc5, 0x24, 0xdb, 0x13, 0xe2, 0x05, 0x44, 0x46, 0x56,
	0xb9, 0xf9, 0x96, 0x84, 0x69, 0xb0, 0x88, 0x33, 0x8f, 0xe6, 0xb7, 0x30, 0xfc, 0x8c, 0x5f, 0x13,
	0x53, 0x08, 0x3b, 0x5d, 0xb8, 0x5a, 0x8a, 0x04, 0x46, 0x64, 0x73, 0x7b, 0xed, 0x15, 0x2d, 0x14,
	0x29, 0x8c, 0x9d, 0x76, 0xf9, 0xe6, 0xb2, 0xd2, 0xdb, 0xda, 0x25, 0x83, 0x34, 0x58, 0x84, 0x59,
	0x9f, 0x9a, 0xff, 0x8c, 0xe0, 0xe4, 0x93, 0xb2, 0x4e, 0x5c, 0x40, 0x44, 0x2a, 0x9b, 0x04, 0xe9,
	0x60, 0x31, 0xbe, 0x98, 0x9d, 0x73, 0x1d, 0x18, 0x3c, 0x27, 0xdf, 0xaf, 0xca, 0xdd, 0x7f, 0xd0,
	0xba, 0xb4, 0x99, 0xcf, 0x9c, 0xfd, 0x19, 0xc2, 0xf4, 0x30, 0x24, 0xde, 0x02, 0x97, 0x4c, 0xc7,
	0x1b, 0x5f, 0xa4, 0xc7, 0xbf, 0xc2, 0x30, 0xe3, 0x74, 0xf1, 0x0e, 0x46, 0x6b, 0x64, 0xa5, 0x4d,
	0x42, 0xf2, 0x7f, 0x4a, 0xc9, 0xa7, 0x68, 0x05, 0xb3, 0x1f, 0x83, 0x63, 0x9d, 0x79, 0x09, 0xc0,
	0xad, 0x70, 0xb9, 0x93, 0xd4, 0x9c, 0x49, 0xd6, 0x63, 0xfa, 0x9d, 0x1b, 0x1c, 0x76, 0xee, 0x15,
	0x4c, 0xec, 0xbd, 0x6a, 0x1a, 0x55, 0xaf, 0x59, 0x7c, 0x42, 0xe2, 0x43, 0x52, 0xcc, 0xe0, 0xb4,
	0xc9, 0x77, 0x9c, 0x30, 0xa4, 0x84, 0x0e, 0xa3, 0x37, 0x1d, 0xf0, 0xc6, 0xa8, 0x42, 0x26, 0x11,
	0xb5, 0xbe, 0xc7, 0xf4, 0x1d, 0x38, 0x65, 0x44, 0x29, 0x87, 0x24, 0x4e, 0x90, 0x8e, 0xe4, 0x27,
	0x78, 0xca, 0x13, 0xec, 0x51, 0x8f, 0x67, 0x1c, 0xff, 0x33, 0x63, 0xac, 0x32, 0x2f, 0xcb, 0x2f,
	0xaa, 0x92, 0x09, 0x70, 0x95, 0x1e, 0xe2, 0xf9, 0xb7, 0x56, 0x9a, 0x6b, 0xed, 0x64, 0x32, 0xa6,
	0x50, 0x87, 0x79, 0x49, 0x2b, 0x55, 0x53, 0xf0, 0x19, 0x05, 0xf7, 0x04, 0x46, 0x2d, 0x96, 0x79,
	0x9d, 0x57, 0x32, 0x99, 0x70, 0xb4, 0x23, 0x66, 0xbf, 0x03, 0x18, 0xf2, 0x3e, 0x1c, 0xdb, 0xd5,
	0xd5, 0xd2, 0x8f, 0xa3, 0x85, 0x18, 0xa1, 0xee, 0xac, 0x96, 0x34, 0x8b, 0x49, 0xd6, 0x42, 0xf4,
	0xa2, 0xbf, 0xe4, 0x75, 0xc2, 0x5e, 0x1d, 0x81, 0x35, 0x30, 0xd8, 0x56, 0xed, 0x0c, 0x5a, 0xfc,
	0xdf, 0x19, 0x9c, 0x41, 0x5c, 0x68, 0xeb, 0xfa, 0xfd, 0xdf, 0x13, 0xd8, 0x59, 0xdb, 0xc8, 0xe2,
	0xa3, 0xdc, 0x91, 0xf3, 0x29, 0x39, 0xf7, 0xa9, 0xf9, 0xaf, 0x00, 0x46, 0x97, 0x7c, 0x71, 0x31,
	0xbb, 0x31, 0xfa, 0x41, 0xd5, 0x85, 0xbc, 0x75, 0xbc, 0xff, 0x71, 0xd6, 0xa7, 0xb0, 0xc2, 0x42,
	0xb9, 0x1d, 0x46, 0xfd, 0x3d, 0xf5, 0x10, 0xb5, 0xa5, 0xb2, 0xce, 0xa8, 0xc2, 0x61, 0x94, 0x77,
	0xb1, 0x4f, 0xa1, 0xd6, 0x7d, 0xd7, 0x35, 0x46, 0xb9, 0x03, 0x2d, 0xe4, 0x1a, 0x6a, 0xab, 0xd6,
	0xb5, 0xe4, 0x25, 0x8c, 0xb3, 0x3d, 0x81, 0x8f, 0x49, 0xa5, 0xef, 0xd4, 0x86, 0xab, 0x8f, 0x33,
	0x8f, 0xfc, 0x4e, 0xe0, 0xc1, 0xa9, 0x6e, 0xde, 0x09, 0x84, 0xf3, 0x07, 0x88, 0x96, 0xd2, 0xe5,
	0x6a, 0x23, 0xde, 0xc3, 0x54, 0x1f, 0x5c, 0x3c, 0x7f, 0xa9, 0x9f, 0x7a, 0x1a, 0x1e, 0x29, 0xc4,
	0x62, 0xef, 0x13, 0x92, 0x78, 0xea, 0xc5, 0xbe, 0x6d, 0x9d, 0xef, 0x5d, 0x44, 0x2f, 0xe6, 0x9b,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x29, 0x65, 0xbf, 0xe3, 0x46, 0x05, 0x00, 0x00,
}
